### PR TITLE
Add TTY support. Fix getStdin.buffer() and tests.

### PR DESCRIPTION
**Pull request by moos**
This implements TTY support per issue #1.

It also fixes the original tests by clearing listeners before each test, and fixing the Promise test for getStdin.buffer() where the assertions were never being called.

With the test fixed, getStdin.buffer() was returning:
```
  TypeError: buf.copy is not a function
    at ReadStream.<anonymous> (D:\dev\github\get-stdin\index.js:56:19)
    at Test.fn (D:\dev\github\get-stdin\test.js:36:16)
```
So fixed this as well, with line 46 in index.js by forcing a new Buffer();

I can submit separate PRs if you prefer -- trying to save myself the hassle of cheery-picking or creating a separate branch!

### CODE REVIEW

**Comment by moos** [comment]
I think the Travis build with Node 0.12 is unrelated.  Can you Kick-off another build?

File: index.js [hunk 1]
```diff
@@ -1,21 +1,24 @@
 'use strict';
 var stdin = process.stdin;
 
-module.exports = function () {
+module.exports = function (opt) {
```
Comment (kevva) [inline index.js]: `opt` => `opts`

File: index.js [hunk 2]
```diff
@@ -1,21 +1,24 @@
...
 	var ret = '';
+	var tty = (opt && 'tty' in opt) ? opt.tty : module.exports.tty;
```
Comment (kevva) [inline index.js]: Add `opts = opts || {}` above `var ret = ''` and change this to `var tty = 'tty' in opts ? opts.tty : module.exports.tty;`

File: package.json [hunk 3]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "get-stdin",
-  "version": "5.0.1",
+  "version": "5.0.2",
```
Comment (kevva) [inline package.json]: Leave the version bump out :).

**Comment by sindresorhus** [comment]
After a lot of thought, I've decided to pass on this. It's just something I would never use and I've honestly never even seen it used. I'd like to preserve the simplicity of this module. I'd suggest you fork and make your own more advanced version of it ;)

**Comment by moos** [comment]
You've never seen "cat > foo" ?

Fair enough, but you many want to consider changing your package name to something like get-stdin-pipe, or update the readme with the limitation that it only reads from pipes.
